[build]
  command = "quarto render"
  publish = "_site"

[build.environment]
  QUARTO_VERSION = "1.4.550"

[context.production]
  command = "curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb && apt-get update && apt-get install -y ./quarto-linux-amd64.deb && quarto render"
